name: Hello world workflow

on:
  push:
    branches:
      -master
  pull_request:
    branches:
      -master
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run : echo " hello world"
        shell: bash
  goodby:
    runs-on: ubuntu-latest
    steps:
      - name: good by world
        run : echo "Goodbye world"
        shell: bash

       
